### ISSUE TITLE
I can't install cocotbext-axi - please help

### ISSUE THREAD

**Issue by hossamfadeel** [alexforencich/cocotbext-axi#30]
I tried the following but I am still getting the same error
`hossam@hossam:~/Projects$ git clone `https://github.com/alexforencich/cocotbext-axi`
```
hossam@hossam:~/Projects$ pip install -e cocotbext-axi 
Obtaining file:///home/hossam/Projects/cocotbext-axi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/hossam/Projects/cocotbext-axi/setup.py", line 2, in <module>
        setup()
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named cocotbext.axi.version
```
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/hossam/Projects/cocotbext-axi/`

Any help will be appreciated.

**Comment by rodrigomelo9** [comment]
Hi. I don't know if you fixed your problem, but it seems related to your python installation. If you need help ask again in your current state and I can suggest solutions. In another case, I think that it issue can be closed @alexforencich (it is old and seems not particularly related to cocotbext-axi).
