### ISSUE TITLE
Uppercase signals are not supported

### ISSUE THREAD

**Issue by rodrigomelo9** [alexforencich/cocotbext-axi#33]
Is not uncommon to have the AXI signals written in uppercase, as in the spec. But if you specify an AXI signal in this way:
```
     1.00ns INFO     test_master failed
                     Traceback (most recent call last):
                       File "/home/rodrigo/repos/0thers-axi/cocotbext-axi/tests/axil/test_axil.py", line 6, in test_master
                         axil_mst = AxiLiteMaster(AxiLiteBus.from_prefix(dut, 'axil'), dut.clk, dut.rst)
                       File "/usr/local/lib/python3.8/dist-packages/cocotbext/axi/axil_channels.py", line 122, in from_prefix
                         write = AxiLiteWriteBus.from_prefix(entity, prefix, **kwargs)
                       File "/usr/local/lib/python3.8/dist-packages/cocotbext/axi/axil_channels.py", line 77, in from_prefix
                         aw = AxiLiteAWBus.from_prefix(entity, prefix, **kwargs)
                       File "/usr/local/lib/python3.8/dist-packages/cocotbext/axi/stream.py", line 49, in from_prefix
                         return cls(entity, prefix, **kwargs)
                       File "/usr/local/lib/python3.8/dist-packages/cocotbext/axi/stream.py", line 41, in __init__
                         super().__init__(entity, prefix, self._signals, optional_signals=self._optional_signals, **kwargs)
                       File "/usr/local/lib/python3.8/dist-packages/cocotb_bus/bus.py", line 62, in __init__
                         self._add_signal(attr_name, signame, array_idx)
                       File "/usr/local/lib/python3.8/dist-packages/cocotb_bus/bus.py", line 79, in _add_signal
                         handle = getattr(self._entity, signame)
                       File "/usr/local/lib/python3.8/dist-packages/cocotb/handle.py", line 346, in __getattr__
                         raise AttributeError(f"{self._name} contains no object named {name}")
                     AttributeError: test_axil contains no object named axil_awaddr
```
I see that `cocotb/handle.py` is not finding the signal, but maybe a "magic" could be performed in the cocotbext-axi side? Or do you have a workaround to recommend me?

**Comment by alexforencich** [comment]
This has been a known issue with the cocotb bus object for a while. I'm planning on making a replacement at some point that is more flexible, but haven't had time to work on it. I'm thinking what's needed is something more mutable, like a general collection of signals that you can add stuff to in a straightforward way. And as part of that, we can make case-insensitive matching possible with case folding.

**Comment by rodrigomelo9** [comment]
I see. What you say is something to also solve #20. Could be great.

In the meantime... Any hack/workaround to convert the signal names of the instantiated dut in lower case? (from the cocotb testbench).
