### ISSUE TITLE
axi address width limitation 

### ISSUE THREAD

**Issue by CharAznable97** [alexforencich/cocotbext-axi#58]
hi, I tried to connect AxiRam with axi interface which has 64 bit addr width...but it resulted into overflow error in C...is this addr size not support in cocotb axi at the moment?

**Comment by davekeeshan** [comment]
What simulator are you using? I have noticed ghdl has problems with things more than 32 bits

**Comment by alexforencich** [comment]
This is probably not a cocotbext-axi problem as it works just fine with address widths of 49 bits, which is used in the corundum testbenches for Zynq. It would be nice to see an actual stack trace though, as it could possibly be a cocotb issue, if not a simulator bug.

**Comment by CharAznable97** [comment]
Hi, I'm using Modelsim simulator running on Linux...the following is the traceback.


#    200.00ns INFO     cocotb.regression                  run_test_001 failed
#                                                         Traceback (most recent call last):
#                                                           File "/home/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cocotb/regression.py", line 719, in _my_test
#                                                             await function(dut, *args, **kwargs)
#                                                           File "/home//test_silex.py", line 91, in run_test
#                                                             tb = TB(dut)
#                                                           File "/home/test_silex.py", line 51, in __init__
#                                                             self.axi_ram = AxiRam(AxiBus.from_prefix(dut, "AxiDma"), dut.refclk, dut.nRst_CPU, size=2**40)
#                                                           File "/home/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cocotbext/axi/axi_ram.py", line 50, in __init__
#                                                             super().__init__(size, mem, **kwargs)
#                                                           File "/home/wangy/.pyenv/versions/3.10.1/lib/python3.10/site-packages/cocotbext/axi/memory.py", line 35, in __init__
#                                                             self.mem = mmap.mmap(-1, size)
#                                                         OverflowError: Python int too large to convert to C ssize_t

**Comment by alexforencich** [comment]
Ah, that's a totally different problem than I thought. Currently the way the AxiRam model is implemented, it uses an mmap, which has to fit in the host system. I have a sparse memory model that I have been working on that lazily allocates bytearrays as the memory is accessed, I'll try to get this added to the repo soon.

In the meantime, turn down the size to maybe a few MB. Specifying a smaller size effectively just truncates some high address bits. Depending on what you're doing in the testbench, this may be acceptable.

**Comment by CharAznable97** [comment]
Thanks, I'll do with the smaller size for now. It should be acceptable. Thanks again for your efforts, I like your cocotb-axi a lot...

**Comment by abyszuk** [comment]
Hi @alexforencich ,

I've just hit a similar problem with the latest version available from `pip`.
This code
```
    ps_ram = AxiRam(AxiBus.from_prefix(tb, 'M_AXI'), tb.S_AXI_ACLK, tb.S_AXI_ARESETN, 2**40)
```
causes this error (Aldec Riviera-Pro simulator):
```
# COUT:      0.00ns INFO     cocotb.regression                  test failed

# COUT:                                                         Traceback (most recent call last):

# COUT:                                                           File "/home/adrian/praca/cce/fgc4/mb/tb/sim_server.py", line 48, in test

# COUT:                                                             ps_ram = AxiRam(AxiBus.from_prefix(tb, 'M_AXI'), tb.S_AXI_ACLK,

# COUT:                                                           File "/home/adrian/.local/lib/python3.10/site-packages/cocotbext/axi/axi_ram.py", line 50, in __init__

# COUT:                                                             super().__init__(size, mem, **kwargs)

# COUT:                                                           File "/home/adrian/.local/lib/python3.10/site-packages/cocotbext/axi/memory.py", line 35, in __init__

# COUT:                                                             self.size = len(self.mem)

# COUT:                                                         OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by alexforencich** [comment]
So, it should be using the sparse memory model now, so mmap failing shouldn't be a problem.  I'm thinking perhaps the call to len() itself may be the problem, perhaps only when running in a 32 bit environment?

There is code like this in memory.py:

        if mem is not None:
            self.mem = mem
        else:
            self.mem = SparseMemory(size)
        self.size = len(self.mem)

Try this:

        self.size = size
        if mem is not None:
            self.mem = mem
            if isinstance(mem, SparseMemory):
                self.size = mem.size
            else:
                self.size = len(mem)
        else:
            self.mem = SparseMemory(size)
