### ISSUE TITLE
Something is broken between 0.1.20 and 0.1.22

### ISSUE THREAD

**Issue by rodrigomelo9** [alexforencich/cocotbext-axi#73]
The same test that PASS with `pip3 install --upgrade cocotbext-axi==0.1.20` FAILS with `0.1.22`:

```
Traceback (most recent call last):
  File "/****/venv/lib/python3.9/site-packages/cocotb/decorators.py", line 262, in f
    res = await cocotb.triggers.with_timeout(
  File "/****/venv/lib/python3.9/site-packages/cocotb/triggers.py", line 1025, in with_timeout
    res = await First(timeout_timer, trigger)
  File "/****/venv/lib/python3.9/site-packages/cocotb/triggers.py", line 906, in _wait
    return await first_trigger  # the first of multiple triggers that fired
  File "/****/venv/lib/python3.9/site-packages/cocotb/triggers.py", line 135, in __await__
    return (yield self)
  File "/****/venv/lib/python3.9/site-packages/cocotb/task.py", line 289, in __await__
    return (yield self)
  File "/****/demos/amba/axil/test.py", line 17, in test_single
    slv = AxiLiteRam(AxiLiteBus.from_prefix(dut, "axil32_t"), dut.xclk)
  File "/****/venv/lib/python3.9/site-packages/cocotbext/axi/axil_ram.py", line 50, in __init__
    super().__init__(size, mem, **kwargs)
  File "/****/venv/lib/python3.9/site-packages/cocotbext/axi/memory.py", line 35, in __init__
    self.size = len(self.mem)
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by linuxbest** [comment]
https://github.com/alexforencich/cocotbext-axi/pull/108
